config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts do
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?



  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_lists(posts)
    html = ''
    posts.each do |post|
      html += render(partial: 'post',locals: { post: post })
    end
    return raw(html)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tenue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Tenue</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } %>
            <%= link_to "投稿する", new_post_path, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <%= form.text_field :image, placeholder: "Image Url" %>
  <%= form.text_area :content, placeholder: "text", rows: "10" %>
  <%= form.submit "SEND" %>
<% end %>

app/views/posts/_post.html.erb
<div class="content_post" style="background-image: url(<%= post.image %>);">
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', post_path(post.id) %>
          </li>
          <% if user_signed_in? && current_user.id == post.user_id %>
          <li>
            <%= link_to '編集', edit_post_path(post.id) %>
          </li>
          <li>
            <%= link_to '削除', post_path(post.id), data: { turbo_method: :delete } %>
          </li>
          <% end %>
        </ul>
      </div>
      <p><%= post.text %></p>
      <span class="name">
        <a href="/users/<%= post.user.id %>">
          <span>投稿者</span><%= post.user.nickname %>
        </a>
      </span>
    </div>

app/views/posts/edit.html.erb
<div class="contents row">
  <div class="container">
    <h3>編集する</h3>
    <%= render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/index.html.erb
<%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <%= post_lists(@posts) %>
</div>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/seach.html.erb
<%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<div class="contents row">
  <% @posts.each do |post| %>
    <%= render partial: "post", locals: { post: post } %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="contents row">
  <div class="content_post" style="background-image: url(<%= @post.image %>);">
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_post_path(@post.id) %>
          </li>
          <li>
            <%= link_to '削除', post_path(@post.id), data: { turbo_method: :delete } %>
          </li>
        </ul>
      </div>
      <% end %>
      <p><%= @post.content %></p>
      <span class="name">
        <a href="/users/<%= @post.user.id %>">
          <span>投稿者</span><%= @post.user.nickname %>
        </a>
      </span>
    </div>
    <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@post, @comment], local: true) do |form| %>
        <%= form.text_area :content, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>:</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="contents row">
  <p><%= @nickname %>さんの投稿一覧</p>
  <% @posts.each do |post| %>
    <%= render partial: "posts/post", locals: { post: post } %>
  <% end %>
</div>